# Generated by Django 3.2.6 on 2021-08-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_to_slip',
            new_name='votes_to_skip',
        ),
    ]
